import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#07006c",
        error: "#ffb4ab",
        primary: "#c0c1ff",
        "surface-container": "#201f22",
        "on-primary-container": "#0d0096",
        "error-container": "#93000a",
        "on-tertiary-container": "#452000",
        "surface-container-highest": "#353437",
        "surface-container-high": "#2a2a2c",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#301400",
        "on-surface": "#e5e1e4",
        "surface-dim": "#131315",
        "secondary-fixed-dim": "#ddb7ff",
        "inverse-surface": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "primary-fixed-dim": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-container": "#d6a9ff",
        "on-secondary": "#490080",
        "tertiary-fixed-dim": "#ffb783",
        "tertiary-container": "#d97721",
        "surface-variant": "#353437",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed-variant": "#703700",
        "surface-tint": "#c0c1ff",
        "inverse-on-surface": "#313032",
        secondary: "#ddb7ff",
        "on-tertiary": "#4f2500",
        "on-surface-variant": "#c7c4d7",
        "surface-bright": "#39393b",
        surface: "#131315",
        "on-background": "#e5e1e4",
        "on-primary": "#1000a9",
        "on-error": "#690005",
        "on-secondary-fixed": "#2c0051",
        background: "#131315",
        "inverse-primary": "#494bd6",
        "outline-variant": "#464554",
        outline: "#908fa0",
        "surface-container-low": "#1c1b1d",
        "on-secondary-fixed-variant": "#6900b3",
        "primary-container": "#8083ff",
        tertiary: "#ffb783",
        "secondary-fixed": "#f0dbff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "stack-lg": "64px",
        "container-max": "1200px",
        "stack-sm": "16px",
        "stack-md": "32px",
        "section-padding": "120px",
      },
      fontFamily: {
        h1: ["Inter", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        h2: ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
